# Generated by Django 3.1.7 on 2021-03-12 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('instituteName', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 9, 13, 17, 237571, tzinfo=utc))),
                ('contactPhone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('numberStudents', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assign', to='membership.salesexecutive')),
                ('workedBy', models.ManyToManyField(related_name='lead_second_assign', to='membership.SalesExecutive')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFeedBack', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 12, 9, 13, 17, 237571, tzinfo=utc))),
                ('rating', models.IntegerField()),
                ('notes', models.TextField()),
                ('nextCallDate', models.DateTimeField()),
                ('demo', models.BooleanField(default=False)),
                ('demoDate', models.DateTimeField()),
                ('feedback', models.CharField(max_length=100)),
                ('furtherCall', models.BooleanField()),
                ('priceQuoted', models.FloatField(default=12000)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_person', to='membership.salesexecutive')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeback_lead', to='sales.lead')),
                ('nextCall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_nextcall', to='membership.salesexecutive')),
            ],
        ),
    ]
