# Generated by Django 3.1.6 on 2021-02-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('instituteName', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('contactPhone', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('numberStudents', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
