# Generated by Django 3.1.6 on 2021-02-11 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210211_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 12, 32, 49, 702717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='numberStudents',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
