# Generated by Django 3.1.6 on 2021-02-11 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('sales', '0003_auto_20210211_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_assign', to='membership.salesexecutive'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workedBy',
            field=models.ManyToManyField(related_name='lead_second_assign', to='membership.SalesExecutive'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 13, 28, 56, 332432, tzinfo=utc)),
        ),
    ]
