# Generated by Django 3.1.6 on 2021-02-12 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 12, 27, 6, 915655, tzinfo=utc)),
        ),
    ]
