# Generated by Django 3.1.6 on 2021-02-13 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210212_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 9, 5, 44, 640616, tzinfo=utc)),
        ),
    ]
