# Generated by Django 3.1.6 on 2021-02-16 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('sales', '0007_auto_20210213_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 19, 24, 42, 118434, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFeedBack', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 2, 16, 19, 24, 42, 119753, tzinfo=utc))),
                ('rating', models.IntegerField()),
                ('notes', models.TextField()),
                ('nextCallDate', models.DateTimeField()),
                ('demo', models.BooleanField(default=False)),
                ('demoDate', models.DateTimeField()),
                ('feedback', models.CharField(max_length=100)),
                ('furtherCall', models.BooleanField()),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_person', to='membership.salesexecutive')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeback_lead', to='sales.lead')),
                ('nextCall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_nextcall', to='membership.salesexecutive')),
            ],
        ),
    ]
