# Generated by Django 3.1.6 on 2021-02-18 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='priceQuoted',
            field=models.FloatField(default=12000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 12, 25, 36, 55833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 12, 25, 36, 54222, tzinfo=utc)),
        ),
    ]
