# Generated by Django 3.1.6 on 2021-03-11 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210218_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 16, 36, 58, 774470, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 16, 36, 58, 773153, tzinfo=utc)),
        ),
    ]
